### ISSUE TITLE
[BUG]: Filtering declarations by subject's function does not consider the latest year of the function's term

### ISSUE THREAD

**Issue by catalin-apostu** [it-pebune/ani-research-web#198]
### Describe the Bug

Filtering declarations by subject's function does not take into account the latest year of the function's term. 
For example, if the period when the declarations were submitted is 2018 - 2022, only declarations up until 2021 are part of the filter's result, while any declaration made in 2022 is not considered.

### Environment

```markdown
- OS:
- Browser:
- Version:
- App Version:
```

**Comment by breta-ionut** [comment]
The feature works as designed actually. The idea is that the filtering takes into account the month and date as well :)

**Comment by catalin-apostu** [comment]
Let's filter only based on month and year. Institution and function name should not be consider in filtering.
