### ISSUE TITLE
As an admin I would like to see the user profile of an user I am administrating

### ISSUE THREAD

**Issue by catalin-apostu** [it-pebune/ani-research-web#6]
User profile
- [ ] Photo (optional, not editable)
- [ ] Name (mandatory, not editable)
- [ ] Email (mandatory, not editable)
- [ ] Phone (optional, not editable)
- [ ] Facebook link (optional, not editable)
- [ ] LinkedIn link (optional, not editable)
- [ ] Notes by Admin or Coordinator (optional, editable)

**Comment by Manu-APO** [comment]
<img width="215" alt="image" src="https://user-images.githubusercontent.com/87855250/153031726-e596f167-5000-4553-9fa3-525d5d4368bc.png">

**Comment by Manu-APO** [comment]
<img width="871" alt="image" src="https://user-images.githubusercontent.com/87855250/153248084-c7b5515a-0cc2-47bb-823f-0c3e12a70a3c.png">
