### ISSUE TITLE
User cannot be logged out

### ISSUE THREAD

**Issue by gbrolt** [it-pebune/ani-research-web#62]
Pressing sign-out button only redirect to login page - you cannot reconnect with another user, as soon as you press 'connect with google' you are automatically logged in with previous user - it does not ask for any credentials.

**Comment by octavianpur** [comment]
Workaround : 

Firefox - Shift + F9 / si se sterge de la Local Storage - tokenul se sterge
![image](https://user-images.githubusercontent.com/25533279/156040322-a9fa2f65-786a-4751-ad74-d0d354ac7036.png)

Chrome - Ctrl + Shift + I - in tabul Application de la Local Storage se da clear la tokenul salvat 
![image](https://user-images.githubusercontent.com/25533279/156041020-5b1a0aa6-f042-4b3b-a6a7-b432cd41673f.png)

**Comment by darakna** [comment]
Cannot be reproduced anymore on:
QA ENV - https://cercetare-qa.integritatepebune.ro/
Backend version: {"v":"0.9.0"}
Frontend version: unknown - Merge pull request https://github.com/it-pebune/ani-research-web/pull/80
